name: Build and Upload SRS

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Download and set up sing-box
        run: |
          curl -fsSL https://sing-box.app/install.sh | sudo sh

      - name: Run compile-rules.js for light version
        run: node compile-rules.js --version=light

      - name: Run compile-rules.js for medium version
        run: node compile-rules.js --version=medium

      - name: Run compile-rules.js for current version
        run: node compile-rules.js --version=full

      - name: Verify compiled-rules.json existence
        run: ls -l compiled-rules-light.json compiled-rules-medium.json compiled-rules-full.json

      - name: Compile light-rules.srs
        run: sing-box rule-set compile --output rsr-security-light.srs compiled-rules-light.json

      - name: Compile medium-rules.srs
        run: sing-box rule-set compile --output rsr-security-medium.srs compiled-rules-medium.json

      - name: Compile full-rules.srs
        run: sing-box rule-set compile --output rsr-security-full.srs compiled-rules-full.json

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rsr-security-light.srs
            rsr-security-medium.srs
            rsr-security-full.srs
          tag_name: "latest"
          name: "Latest Build"
          body: "This is the latest automated build of the rule sets."
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 