name: Build and Upload SRS

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Download and set up sing-box
        run: |
          LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r '.assets[] | select(.name | contains("linux-amd64.tar.gz")) | .browser_download_url')
          LATEST_VERSION=$(echo "$LATEST_RELEASE_URL" | grep -oP 'v[0-9]+\.[0-9]+\.[0-9]+')
          FILENAME="sing-box-${LATEST_VERSION:1}-linux-amd64.tar.gz"
          wget -O "$FILENAME" "$LATEST_RELEASE_URL"
          tar -xvf "$FILENAME"
          sudo mv "sing-box-${LATEST_VERSION:1}-linux-amd64/sing-box" /usr/local/bin

      - name: Run compile-rules.js
        run: node compile-rules.js

      - name: Compile custom-rules.srs
        run: sing-box rule-set compile --output rsr-security.srs compiled-rules.json

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: rsr-security.srs
          tag_name: "hourly-${{ github.run_number }}"
          name: "Hourly Build ${{ github.run_number }}"
          body: "This is an automated hourly build of custom-rules.srs."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 